version: '3.8'

services:
  todo-app:
      build: .
      container_name: todo-app
      ports:
        - "8080:8080"
      environment:
        # DB environment
        - DATABASE_URL="postgres://postgres:password@db:5432/todo-app?sslmode=disabled&pool_max_conns=10"
        # service port
        - SERVER_PORT=8080
      depends_on:
        db:
            condition: service_healthy
      networks:
        - internal
  
  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo-app
    volumes:
      # "./migrations/init.sql" - DB migrations path
      - ./migrations/init.up.sql:/docker-entrypoint-initdb.d/init.up.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d todo-app'"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - internal
networks:
  internal: